Update automation dependencies, partially to fix an error that comes up when running the tests locally:
```
An exception or error caused a run to abort: spray.json.package$.enrichString(Ljava/lang/String;)Lspray/json/RichString;
java.lang.NoSuchMethodError: spray.json.package$.enrichString(Ljava/lang/String;)Lspray/json/RichString;
	at org.broadinstitute.dsde.workbench.config.CommonConfig$CommonUsers.$init$(CommonConfig.scala:14)
	```